#External Prior/Transform Input
extrinsics:
  mapFrame: map
  odomFrame: odom
  baseFootprintFrame: base_footprint
  lidarFrame: lidar_3d_straight        #LiDAR frame name - used to lookup LiDAR-to-ExternalSensor Frame
  imuFrame: imu     # IMU_CABIN_link           #Frame of IMU used in integrator - Used for lookup transform to lidarFrame
  

